import IDefinedProduct from "./IDefinedProduct.js";
import ISKOSConcept from "./ISKOSConcept.js";
import IAllergenCharacteristic from "./IAllergenCharacteristic.js";
import INutrientCharacteristic from "./INutrientCharacteristic.js";
import IPhysicalCharacteristic from "./IPhysicalCharacteristic.js";
import ICatalogItem from "./ICatalogItem.js";
import IQuantity from "./IQuantity.js";
import { SemanticObject } from "@virtual-assembly/semantizer";
import { Semanticable } from "@virtual-assembly/semantizer";
import IConnector from "./IConnector.js";
import IGetterOptions from "./IGetterOptions.js";
export default abstract class DefinedProduct extends SemanticObject implements IDefinedProduct {
    protected connector: IConnector;
    protected constructor(parameters: {
        connector: IConnector;
        semanticId?: string;
        semanticType?: string;
        other?: Semanticable;
        name?: string;
        description?: string;
        productType?: ISKOSConcept;
        quantity?: IQuantity;
        alcoholPercentage?: number;
        lifetime?: string;
        claims?: ISKOSConcept[];
        usageOrStorageConditions?: string;
        allergenCharacteristics?: IAllergenCharacteristic[];
        nutrientCharacteristics?: INutrientCharacteristic[];
        physicalCharacteristics?: IPhysicalCharacteristic[];
        geographicalOrigin?: ISKOSConcept;
        catalogItems?: ICatalogItem[];
        certifications?: ISKOSConcept[];
        natureOrigin?: ISKOSConcept[];
        partOrigin?: ISKOSConcept[];
        images?: string[];
        variants?: IDefinedProduct[];
        isVariantOf?: IDefinedProduct[];
        doNotStore?: boolean;
    });
    removeClaim(claim: ISKOSConcept): void;
    setName(name: string): void;
    addCatalogItem(catalogItem: ICatalogItem): void;
    setVariants(variants: IDefinedProduct[]): void;
    addIsVariantOf(parent: IDefinedProduct): void;
    addCertification(certification: ISKOSConcept): void;
    addClaim(claim: ISKOSConcept): void;
    getQuantity(): IQuantity | undefined;
    setProductType(productType: ISKOSConcept): void;
    getVariants(options?: IGetterOptions): Promise<IDefinedProduct[]>;
    getUsageOrStorageConditions(): string | undefined;
    getNutrientCharacteristics(options?: IGetterOptions): Promise<INutrientCharacteristic[]>;
    addPartOrigin(partOrigin: ISKOSConcept): void;
    removeNatureOrigin(natureOrigin: ISKOSConcept): void;
    removeCertification(certification: ISKOSConcept): void;
    removePartOrigin(partOrigin: ISKOSConcept): void;
    setIsVariantOf(parents: IDefinedProduct[]): void;
    removePhysicalCharacteristic(physicalCharacteristic: IPhysicalCharacteristic): void;
    setLifetime(lifetime: string): void;
    addPhysicalCharacteristic(physicalCharacteristic: IPhysicalCharacteristic): void;
    removeVariant(variant: IDefinedProduct): void;
    getIsVariantOf(options?: IGetterOptions): Promise<IDefinedProduct[]>;
    getProductType(options?: IGetterOptions): Promise<ISKOSConcept | undefined>;
    getPartOrigin(options?: IGetterOptions): Promise<ISKOSConcept[]>;
    getNatureOrigin(options?: IGetterOptions): Promise<ISKOSConcept[]>;
    getGeographicalOrigin(options?: IGetterOptions): Promise<ISKOSConcept | undefined>;
    getImages(): string[];
    getDescription(): string | undefined;
    setGeographicalOrigin(geographicalOrigin: ISKOSConcept): void;
    addNutrientCharacteristic(nutrientCharacteristic: INutrientCharacteristic): void;
    setQuantity(quantity: IQuantity): void;
    addAllergenCharacteristic(allergenCharacteristic: IAllergenCharacteristic): void;
    getClaims(options?: IGetterOptions): Promise<ISKOSConcept[]>;
    removeImage(image: string): void;
    addNatureOrigin(natureOrigin: ISKOSConcept): void;
    addVariant(variant: IDefinedProduct): void;
    getAlcoholPercentage(): number | undefined;
    removeAllergenCharacteristic(allergenCharacteristic: IAllergenCharacteristic): void;
    removeNutrientCharacteristic(nutrientCharacteristic: INutrientCharacteristic): void;
    getName(): string | undefined;
    removeIsVariantOf(parent: IDefinedProduct): void;
    setAlcoholPercentage(alcoholPercentage: number): void;
    getCatalogItems(options?: IGetterOptions): Promise<ICatalogItem[]>;
    getCertifications(options?: IGetterOptions): Promise<ISKOSConcept[]>;
    getLifetime(): string | undefined;
    setDescription(description: string): void;
    setUsageOrStorageConditions(usageOrStorageConditions: string): void;
    getAllergenCharacteristics(options?: IGetterOptions): Promise<IAllergenCharacteristic[]>;
    addImage(image: string): void;
    getPhysicalCharacteristics(options?: IGetterOptions): Promise<IPhysicalCharacteristic[]>;
}
//# sourceMappingURL=DefinedProduct.d.ts.map